apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
    group: iot
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
        group: customer
        tier: frontend
    spec:
      containers:
      - name: phpmyadmin
        image: campbellsoftwaresolutions/osticket
        env:
        - name: MYSQL_HOST
          value: osticket-mysql
        - name: MYSQL_PASSWORD
          value: secret        
        ports:
        - containerPort: 80
          name: phpmyadmin
